version: "3.9"

services:
  mizili-e-commerce-frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app  # Maps the current directory (.) to /app in the container
    environment:
      - CHOKIDAR_USEPOLLING=true  

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/src:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_NAME=mizili
      - DB_USER=mizili
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:

