backend:
  build:
    context: ./backend
    dockerfile: Dockerfile
  command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  volumes:
    - ./backend/src:/app
  ports:
    - "8000:8000"
  environment:
    - DEBUG=True
    - DB_NAME=mizili
    - DB_USER=mizili
    - DB_PASSWORD=password
    - DB_HOST=db
    - DB_PORT=5432
    # superuser credentials
    - DJANGO_SUPERUSER_USERNAME=admin
    - DJANGO_SUPERUSER_PASSWORD=admin123
    - DJANGO_SUPERUSER_EMAIL=admin@example.com
